#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : typeguard
Version  : 2.12.1
Release  : 16
URL      : https://files.pythonhosted.org/packages/55/ba/8e6dd2fa02d95712e0e2ca0705f2f988287538f6927bba3ec0ceb719e708/typeguard-2.12.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/55/ba/8e6dd2fa02d95712e0e2ca0705f2f988287538f6927bba3ec0ceb719e708/typeguard-2.12.1.tar.gz
Summary  : Run-time type checker for Python
Group    : Development/Tools
License  : MIT
Requires: typeguard-license = %{version}-%{release}
Requires: typeguard-python = %{version}-%{release}
Requires: typeguard-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools_scm
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://travis-ci.com/agronholm/typeguard.svg?branch=master
:target: https://travis-ci.com/agronholm/typeguard
:alt: Build Status
.. image:: https://coveralls.io/repos/agronholm/typeguard/badge.svg?branch=master&service=github
:target: https://coveralls.io/github/agronholm/typeguard?branch=master
:alt: Code Coverage
.. image:: https://readthedocs.org/projects/typeguard/badge/?version=latest
:target: https://typeguard.readthedocs.io/en/latest/?badge=latest

%package license
Summary: license components for the typeguard package.
Group: Default

%description license
license components for the typeguard package.


%package python
Summary: python components for the typeguard package.
Group: Default
Requires: typeguard-python3 = %{version}-%{release}

%description python
python components for the typeguard package.


%package python3
Summary: python3 components for the typeguard package.
Group: Default
Requires: python3-core
Provides: pypi(typeguard)

%description python3
python3 components for the typeguard package.


%prep
%setup -q -n typeguard-2.12.1
cd %{_builddir}/typeguard-2.12.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629142609
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/typeguard
cp %{_builddir}/typeguard-2.12.1/LICENSE %{buildroot}/usr/share/package-licenses/typeguard/a51ccdcb7a9d8c2116d1dfc16f11b3c8a5830f67
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/typeguard/a51ccdcb7a9d8c2116d1dfc16f11b3c8a5830f67

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
